branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

sudo: false
os: osx
language: ruby
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - source ~/.bashrc
  - nvm install 4
  - nvm use 4
  - npm install npm -g

install:
  - npm install

before_script:
  - npm prune

script:
  - npm run test
  - npm run build

after_success:
  - >
    npm run semantic-release-prepare &&
    export TRAVIS_TAG=v$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]') &&
    npm run semantic-release-publish

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: "./release/darwin-x64/Orchestra.dmg"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
    secure: FRiq35XYnKOsMDPjk2gOzut0sTK+Pa16EWpZxJmcsfNctELQ/9pVMYuLQhYYZ4Ewf4qUV+h0+lkbsG0sZacyjvlcI7pluD43mn9TyP1N2KM4L+Hp6f941gtOvLuhN2UyVM5iYWPdrMHEhuOw0foxRy8gyZJ5dJE7IJmP/Xgar4I=
